# Generated by Django 3.0.7 on 2020-06-25 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('main_photo', models.ImageField(upload_to='photos/accessories/', verbose_name='Imagem')),
                ('plataform', models.CharField(max_length=200, verbose_name='Plataforma')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Accessório',
                'ordering': ('-created_at',),
            },
        ),
    ]
