# Generated by Django 3.0.7 on 2020-06-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_auto_20200629_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessories',
            options={'ordering': ('name',), 'verbose_name': 'Acessório'},
        ),
    ]
