# Generated by Django 3.0.7 on 2020-06-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='main_photo',
            field=models.ImageField(upload_to='photos/games/', verbose_name='Imagem'),
        ),
    ]
