# Generated by Django 3.0.7 on 2020-06-25 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consoles',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='main_photo',
            field=models.ImageField(upload_to='photos/consoles/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='plataform',
            field=models.CharField(max_length=200, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
    ]
